module.exports = [
  {
    id: 1,
    name: "Pilot Battle",
    date: "2023-01-23",
    plays: [
      {
        id: 1,
        name: "Simply Square",
        solution: require("./001-simply-square"),
        date: "2023-01-23",
      },
      {
        id: 2,
        name: "Carrom",
        solution: require("./002-carrom"),
        date: "2023-01-23",
      },
      {
        id: 3,
        name: "Push Button",
        solution: require("./003-push-button"),
        date: "2023-01-23",
      },
      {
        id: 4,
        name: "Ups n Downs",
        solution: require("./004-ups-n-downs"),
        date: "2023-01-23",
      },
      {
        id: 5,
        name: "Acid Rain",
        solution: require("./005-acid-rain"),
        date: "2023-01-23",
      },
      {
        id: 6,
        name: "Missing Slice",
        solution: require("./006-missing-slice"),
        date: "2023-01-23",
      },
      {
        id: 7,
        name: "Leafy Trail",
        solution: require("./007-leafy-trail"),
        date: "2023-01-23",
      },
      {
        id: 8,
        name: "Forking Crazy",
        solution: require("./008-forking-crazy"),
        date: "2023-01-23",
      },
      {
        id: 9,
        name: "Tesseract",
        solution: require("./009-tesseract"),
        date: "2023-01-23",
      },
      {
        id: 10,
        name: "Cloaked Spirits",
        solution: require("./010-cloaked-sprits"),
        date: "2023-01-23",
      },
      {
        id: 11,
        name: "Eye of sauron",
        solution: require("./011-eye-of-sauron"),
        date: "2023-01-23",
      },
      {
        id: 12,
        name: "Wiggly Moustache",
        solution: require("./012-wiggly-moustache"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 2,
    name: "Visibility",
    date: "2023-01-23",
    plays: [
      {
        id: 13,
        name: "Totally Triangle",
        solution: require("./013-totally_triangle"),
        date: "2023-01-23",
      },
      {
        id: 14,
        name: "Web Maker Logo",
        solution: require("./014-web_maker_logo"),
        date: "2023-01-23",
      },
      {
        id: 15,
        name: "Overlap",
        solution: require("./015-overlap"),
        date: "2023-01-23",
      },
      {
        id: 16,
        name: "Eye of the Tiger",
        solution: require("./016-eye_of_the_tiger"),
        date: "2023-01-23",
      },
      {
        id: 17,
        name: "Fidget Spinner",
        solution: require("./017-fidget_spinner"),
        date: "2023-01-23",
      },
      {
        id: 18,
        name: "Matrix",
        solution: require("./018-matrix"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 3,
    name: "Cube",
    date: "2023-01-23",
    plays: [
      {
        id: 19,
        name: "Cube",
        solution: require("./019-cube"),
        date: "2023-01-23",
      },
      {
        id: 20,
        name: "Ticket",
        solution: require("./020-ticket"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 4,
    name: "Display",
    date: "2023-01-23",
    plays: [
      {
        id: 21,
        name: "SitePoint Logo",
        solution: require("./021-sitepoint_logo"),
        date: "2023-01-23",
      },
      {
        id: 22,
        name: "Cloud",
        solution: require("./022-cloud"),
        date: "2023-01-23",
      },
      {
        id: 23,
        name: "Boxception",
        solution: require("./023-boxception"),
        date: "2023-01-23",
      },
      {
        id: 24,
        name: "Switches",
        solution: require("./024-switches"),
        date: "2023-01-23",
      },
      {
        id: 25,
        name: "Blossom",
        solution: require("./025-blossom"),
        date: "2023-01-23",
      },
      {
        id: 26,
        name: "Smiley",
        solution: require("./026-smiley"),
        date: "2023-01-23",
      },
      {
        id: 27,
        name: "Lock up",
        solution: require("./027-lock_up"),
        date: "2023-01-23",
      },
      {
        id: 28,
        name: "Cups and Balls",
        solution: require("./028-cups_&_balls"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 5,
    name: "Inline",
    date: "2023-01-23",
    plays: [
      {
        id: 29,
        name: "Suffocate",
        solution: require("./029-suffocate"),
        date: "2023-01-23",
      },
      {
        id: 30,
        name: "Horizon",
        solution: require("./030-horizon"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 6,
    name: "Conic",
    date: "2023-01-23",
    plays: [
      {
        id: 31,
        name: "Equals",
        solution: require("./031-equals"),
        date: "2023-01-23",
      },
      {
        id: 32,
        name: "Band-aid",
        solution: require("./032-band-aid"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 7,
    name: "Backface",
    date: "2023-01-23",
    plays: [
      {
        id: 33,
        name: "Birdie",
        solution: require("./033-birdie"),
        date: "2023-01-23",
      },
      {
        id: 34,
        name: "Chrismas Tree",
        solution: require("./034-chrismas_tree"),
        date: "2023-01-23",
      },
      {
        id: 35,
        name: "Ice Cream",
        solution: require("./035-ice_cream"),
        date: "2023-01-23",
      },
      {
        id: 36,
        name: "Interleaved",
        solution: require("./036-interleaved"),
        date: "2023-01-23",
      },
      {
        id: 37,
        name: "Tunnel",
        solution: require("./037-tunnel"),
        date: "2023-01-23",
      },
      {
        id: 38,
        name: "Not Simply Square",
        solution: require("./038-not_simply_square"),
        date: "2023-01-23",
      },
      {
        id: 39,
        name: "Sunset",
        solution: require("./039-sunset"),
        date: "2023-01-23",
      },
      {
        id: 40,
        name: "Letter B",
        solution: require("./040-letter_b"),
        date: "2023-01-23",
      },
      {
        id: 41,
        name: "Fox Head",
        solution: require("./041-fox_head"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 8,
    name: "Transition",
    date: "2023-01-23",
    plays: [
      {
        id: 42,
        name: "Baby",
        solution: require("./042-baby"),
        date: "2023-01-23",
      },
      {
        id: 43,
        name: "Wrench",
        solution: require("./043-wrench"),
        date: "2023-01-23",
      },
      {
        id: 44,
        name: "Stripes",
        solution: require("./044-stripes"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 9,
    name: "Margin",
    date: "2023-01-23",
    plays: [
      {
        id: 45,
        name: "Magical Tree",
        solution: require("./045-magical_tree"),
        date: "2023-01-23",
      },
      {
        id: 46,
        name: "Mountains",
        solution: require("./046-mountains"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 10,
    name: "Block",
    date: "2023-02-18",
    plays: [
      {
        id: 47,
        name: "Corona Virus",
        solution: require("./047-corona-virus.js"),
        date: "2023-02-18",
      },
      {
        id: 48,
        name: "Wash Your Hands",
        solution: require("./048-wash-your-hands.js"),
        date: "2023-02-18",
      },
      {
        id: 49,
        name: "Stay at Home",
        solution: require("./049-stay-at-home.js"),
        date: "2023-02-18",
      },
      {
        id: 50,
        name: "Use Hand Sanitizer",
        solution: require("./050-use-hand-sanitizer.js"),
        date: "2023-02-18",
      },
      {
        id: 51,
        name: "Wear a Mask",
        solution: require("./051-wear-a-mask.js"),
        date: "2023-02-18",
      },
      {
        id: 52,
        name: "Break the Chain",
        solution: require("./052-break-the-chain.js"),
        date: "2023-02-18",
      },
    ],
  },
  {
    id: 11,
    name: "Overflow",
    date: "2023-03-15",
    plays: [
      {
        id: 53,
        name: "Pastel Logo",
        solution: require("./053-pastel-logo.js"),
        date: "2023-03-15",
      },
      {
        id: 54,
        name: "Black Lives Matter",
        solution: require("./054-black-lives-matter"),
        date: "2023-03-15",
      },
      {
        id: 55,
        name: "Windmill",
        solution: require("./055-windmill"),
        date: "2023-03-15",
      },
      {
        id: 56,
        name: "Skull",
        solution: require("./056-skull"),
        date: "2023-03-15",
      },
      {
        id: 57,
        name: "Pillars",
        solution: require("./057-pillars"),
        date: "2023-03-15",
      },
      {
        id: 58,
        name: "Rose",
        solution: require("./058-rose"),
        date: "2023-03-15",
      },
      {
        id: 59,
        name: "Earth",
        solution: require("./059-earth"),
        date: "2023-03-15",
      },
      {
        id: 60,
        name: "Evil Triangles",
        solution: require("./060-evil-triangles"),
        date: "2023-03-15",
      },
    ],
  },
  {
    id: 12,
    name: "Blend",
    date: "2023-04-06",
    plays: [
      {
        id: 61,
        name: "ImproveMX",
        solution: require("./061-improvemx"),
        date: "2023-04-06",
      },
      {
        id: 62,
        name: "Sunset",
        solution: require("./062-sunset"),
        date: "2023-04-06",
      },
      {
        id: 63,
        name: "Command Key",
        solution: require("./063-command-key"),
        date: "2023-04-06",
      },
      {
        id: 64,
        name: "Door knob",
        solution: require("./064-door-knob"),
        date: "2023-04-06",
      },
      {
        id: 65,
        name: "Max Volume",
        solution: require("./065-max-volume"),
        date: "2023-04-06",
      },
      {
        id: 66,
        name: "Batmicky",
        solution: require("./066-batmicky"),
        date: "2023-04-06",
      },
      {
        id: 67,
        name: "Video reel",
        solution: require("./067-video-reel"),
        date: "2023-04-06",
      },
      {
        id: 68,
        name: "Bell",
        solution: require("./068-bell"),
        date: "2023-04-06",
      },
    ],
  },
  {
    id: 13,
    name: "Clip",
    date: "2023-06-25",
    plays: [
      {
        id: 69,
        name: "PushOwl",
        solution: require("./069-pushowl"),
        date: "2023-06-25",
      },
      {
        id: 70,
        name: "Froggy",
        solution: require("./070-froggy"),
        date: "2023-06-25",
      },
      {
        id: 71,
        name: "Elephant",
        solution: require("./071-elephant"),
        date: "2023-06-25",
      },
      {
        id: 72,
        name: "Sheep",
        solution: require("./072-sheep"),
        date: "2023-06-25",
      },
      {
        id: 73,
        name: "Happy Tiger",
        solution: require("./073-happy-tiger"),
        date: "2023-06-25",
      },
      {
        id: 74,
        name: "Danger Noodle",
        solution: require("./074-danger-noodle"),
        date: "2023-06-25",
      },
      {
        id: 75,
        name: "Hippo",
        solution: require("./075-hippo"),
        date: "2023-06-25",
      },
      {
        id: 76,
        name: "Beeee",
        solution: require("./076-beeee"),
        date: "2023-06-25",
      },
    ],
  },
  {
    id: 14,
    name: "ZIndex",
    date: "2023-06-26",
    plays: [],
  },
  {
    id: 24,
    name: "Offset",
    date: "2023-04-22",
    plays: [
      {
        id: 143,
        name: "Simply Circle",
        solution: require("./143-simply-circle"),
        date: "2023-04-22",
      },
      {
        id: 144,
        name: "Long Heart",
        solution: require("./144-long-heart"),
        date: "2023-04-22",
      },
      {
        id: 145,
        name: "Spotlight",
        solution: require("./145-spotlight"),
        date: "2023-04-22",
      },
      {
        id: 146,
        name: "Streaks",
        solution: require("./146-streaks"),
        date: "2023-04-22",
      },
      {
        id: 147,
        name: "Splash",
        solution: require("./147-splash"),
        date: "2023-04-22",
      },
      {
        id: 148,
        name: "Eight",
        solution: require("./148-eight"),
        date: "2023-04-22",
      },
      {
        id: 149,
        name: "Earthworm",
        solution: require("./149-earthworm"),
        date: "2023-04-22",
      },
      {
        id: 150,
        name: "Finger Heart",
        solution: require("./150-finger-heart"),
        date: "2023-04-22",
      },
    ],
  },
];
