module.exports = [
  {
    id: 1,
    name: "Pilot Battle",
    date: "2023-01-23",
    plays: [
      {
        id: 1,
        name: "Simply Square",
        solution: require("./001-simply-square"),
        date: "2023-01-23",
      },
      {
        id: 2,
        name: "Carrom",
        solution: require("./002-carrom"),
        date: "2023-10-12",
      },
      {
        id: 3,
        name: "Push Button",
        solution: require("./003-push-button"),
        date: "2023-01-23",
      },
      {
        id: 4,
        name: "Ups n Downs",
        solution: require("./004-ups-n-downs"),
        date: "2023-01-23",
      },
      {
        id: 5,
        name: "Acid Rain",
        solution: require("./005-acid-rain"),
        date: "2023-01-23",
      },
      {
        id: 6,
        name: "Missing Slice",
        solution: require("./006-missing-slice"),
        date: "2023-01-23",
      },
      {
        id: 7,
        name: "Leafy Trail",
        solution: require("./007-leafy-trail"),
        date: "2023-01-23",
      },
      {
        id: 8,
        name: "Forking Crazy",
        solution: require("./008-forking-crazy"),
        date: "2023-01-23",
      },
      {
        id: 9,
        name: "Tesseract",
        solution: require("./009-tesseract"),
        date: "2023-01-23",
      },
      {
        id: 10,
        name: "Cloaked Spirits",
        solution: require("./010-cloaked-sprits"),
        date: "2023-01-23",
      },
      {
        id: 11,
        name: "Eye of sauron",
        solution: require("./011-eye-of-sauron"),
        date: "2023-01-23",
      },
      {
        id: 12,
        name: "Wiggly Moustache",
        solution: require("./012-wiggly-moustache"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 2,
    name: "Visibility",
    date: "2023-01-23",
    plays: [
      {
        id: 13,
        name: "Totally Triangle",
        solution: require("./013-totally_triangle"),
        date: "2023-01-23",
      },
      {
        id: 14,
        name: "Web Maker Logo",
        solution: require("./014-web_maker_logo"),
        date: "2023-01-23",
      },
      {
        id: 15,
        name: "Overlap",
        solution: require("./015-overlap"),
        date: "2023-01-23",
      },
      {
        id: 16,
        name: "Eye of the Tiger",
        solution: require("./016-eye_of_the_tiger"),
        date: "2023-01-23",
      },
      {
        id: 17,
        name: "Fidget Spinner",
        solution: require("./017-fidget_spinner"),
        date: "2023-01-23",
      },
      {
        id: 18,
        name: "Matrix",
        solution: require("./018-matrix"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 3,
    name: "Cube",
    date: "2023-01-23",
    plays: [
      {
        id: 19,
        name: "Cube",
        solution: require("./019-cube"),
        date: "2023-01-23",
      },
      {
        id: 20,
        name: "Ticket",
        solution: require("./020-ticket"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 4,
    name: "Display",
    date: "2023-01-23",
    plays: [
      {
        id: 21,
        name: "SitePoint Logo",
        solution: require("./021-sitepoint_logo"),
        date: "2023-01-23",
      },
      {
        id: 22,
        name: "Cloud",
        solution: require("./022-cloud"),
        date: "2023-01-23",
      },
      {
        id: 23,
        name: "Boxception",
        solution: require("./023-boxception"),
        date: "2023-01-23",
      },
      {
        id: 24,
        name: "Switches",
        solution: require("./024-switches"),
        date: "2023-01-23",
      },
      {
        id: 25,
        name: "Blossom",
        solution: require("./025-blossom"),
        date: "2023-01-23",
      },
      {
        id: 26,
        name: "Smiley",
        solution: require("./026-smiley"),
        date: "2023-10-12",
      },
      {
        id: 27,
        name: "Lock up",
        solution: require("./027-lock_up"),
        date: "2023-01-23",
      },
      {
        id: 28,
        name: "Cups and Balls",
        solution: require("./028-cups_&_balls"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 5,
    name: "Inline",
    date: "2023-01-23",
    plays: [
      {
        id: 29,
        name: "Suffocate",
        solution: require("./029-suffocate"),
        date: "2023-01-23",
      },
      {
        id: 30,
        name: "Horizon",
        solution: require("./030-horizon"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 6,
    name: "Conic",
    date: "2023-01-23",
    plays: [
      {
        id: 31,
        name: "Equals",
        solution: require("./031-equals"),
        date: "2023-01-23",
      },
      {
        id: 32,
        name: "Band-aid",
        solution: require("./032-band-aid"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 7,
    name: "Backface",
    date: "2023-01-23",
    plays: [
      {
        id: 33,
        name: "Birdie",
        solution: require("./033-birdie"),
        date: "2023-01-23",
      },
      {
        id: 34,
        name: "Chrismas Tree",
        solution: require("./034-chrismas_tree"),
        date: "2023-01-23",
      },
      {
        id: 35,
        name: "Ice Cream",
        solution: require("./035-ice_cream"),
        date: "2023-01-23",
      },
      {
        id: 36,
        name: "Interleaved",
        solution: require("./036-interleaved"),
        date: "2023-01-23",
      },
      {
        id: 37,
        name: "Tunnel",
        solution: require("./037-tunnel"),
        date: "2023-01-23",
      },
      {
        id: 38,
        name: "Not Simply Square",
        solution: require("./038-not_simply_square"),
        date: "2023-01-23",
      },
      {
        id: 39,
        name: "Sunset",
        solution: require("./039-sunset"),
        date: "2023-01-23",
      },
      {
        id: 40,
        name: "Letter B",
        solution: require("./040-letter_b"),
        date: "2023-01-23",
      },
      {
        id: 41,
        name: "Fox Head",
        solution: require("./041-fox_head"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 8,
    name: "Transition",
    date: "2023-01-23",
    plays: [
      {
        id: 42,
        name: "Baby",
        solution: require("./042-baby"),
        date: "2023-01-23",
      },
      {
        id: 43,
        name: "Wrench",
        solution: require("./043-wrench"),
        date: "2023-01-23",
      },
      {
        id: 44,
        name: "Stripes",
        solution: require("./044-stripes"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 9,
    name: "Margin",
    date: "2023-01-23",
    plays: [
      {
        id: 45,
        name: "Magical Tree",
        solution: require("./045-magical_tree"),
        date: "2023-01-23",
      },
      {
        id: 46,
        name: "Mountains",
        solution: require("./046-mountains"),
        date: "2023-01-23",
      },
    ],
  },
  {
    id: 10,
    name: "Block",
    date: "2023-02-18",
    plays: [
      {
        id: 47,
        name: "Corona Virus",
        solution: require("./047-corona-virus.js"),
        date: "2023-02-18",
      },
      {
        id: 48,
        name: "Wash Your Hands",
        solution: require("./048-wash-your-hands.js"),
        date: "2023-02-18",
      },
      {
        id: 49,
        name: "Stay at Home",
        solution: require("./049-stay-at-home.js"),
        date: "2023-02-18",
      },
      {
        id: 50,
        name: "Use Hand Sanitizer",
        solution: require("./050-use-hand-sanitizer.js"),
        date: "2023-02-18",
      },
      {
        id: 51,
        name: "Wear a Mask",
        solution: require("./051-wear-a-mask.js"),
        date: "2023-02-18",
      },
      {
        id: 52,
        name: "Break the Chain",
        solution: require("./052-break-the-chain.js"),
        date: "2023-02-18",
      },
    ],
  },
  {
    id: 11,
    name: "Overflow",
    date: "2023-03-15",
    plays: [
      {
        id: 53,
        name: "Pastel Logo",
        solution: require("./053-pastel-logo.js"),
        date: "2023-03-15",
      },
      {
        id: 54,
        name: "Black Lives Matter",
        solution: require("./054-black-lives-matter"),
        date: "2023-03-15",
      },
      {
        id: 55,
        name: "Windmill",
        solution: require("./055-windmill"),
        date: "2023-03-15",
      },
      {
        id: 56,
        name: "Skull",
        solution: require("./056-skull"),
        date: "2023-03-15",
      },
      {
        id: 57,
        name: "Pillars",
        solution: require("./057-pillars"),
        date: "2023-03-15",
      },
      {
        id: 58,
        name: "Rose",
        solution: require("./058-rose"),
        date: "2023-03-15",
      },
      {
        id: 59,
        name: "Earth",
        solution: require("./059-earth"),
        date: "2023-03-15",
      },
      {
        id: 60,
        name: "Evil Triangles",
        solution: require("./060-evil-triangles"),
        date: "2023-03-15",
      },
    ],
  },
  {
    id: 12,
    name: "Blend",
    date: "2023-04-06",
    plays: [
      {
        id: 61,
        name: "ImproveMX",
        solution: require("./061-improvemx"),
        date: "2023-10-12",
      },
      {
        id: 62,
        name: "Sunset",
        solution: require("./062-sunset"),
        date: "2023-04-06",
      },
      {
        id: 63,
        name: "Command Key",
        solution: require("./063-command-key"),
        date: "2023-04-06",
      },
      {
        id: 64,
        name: "Door knob",
        solution: require("./064-door-knob"),
        date: "2023-04-06",
      },
      {
        id: 65,
        name: "Max Volume",
        solution: require("./065-max-volume"),
        date: "2023-04-06",
      },
      {
        id: 66,
        name: "Batmicky",
        solution: require("./066-batmicky"),
        date: "2023-04-06",
      },
      {
        id: 67,
        name: "Video reel",
        solution: require("./067-video-reel"),
        date: "2023-04-06",
      },
      {
        id: 68,
        name: "Bell",
        solution: require("./068-bell"),
        date: "2023-04-06",
      },
    ],
  },
  {
    id: 13,
    name: "Clip",
    date: "2023-06-25",
    plays: [
      {
        id: 69,
        name: "PushOwl",
        solution: require("./069-pushowl"),
        date: "2023-06-25",
      },
      {
        id: 70,
        name: "Froggy",
        solution: require("./070-froggy"),
        date: "2023-06-25",
      },
      {
        id: 71,
        name: "Elephant",
        solution: require("./071-elephant"),
        date: "2023-06-25",
      },
      {
        id: 72,
        name: "Sheep",
        solution: require("./072-sheep"),
        date: "2023-06-25",
      },
      {
        id: 73,
        name: "Happy Tiger",
        solution: require("./073-happy-tiger"),
        date: "2023-06-25",
      },
      {
        id: 74,
        name: "Danger Noodle",
        solution: require("./074-danger-noodle"),
        date: "2023-06-25",
      },
      {
        id: 75,
        name: "Hippo",
        solution: require("./075-hippo"),
        date: "2023-06-25",
      },
      {
        id: 76,
        name: "Beeee",
        solution: require("./076-beeee"),
        date: "2023-06-25",
      },
    ],
  },
  {
    id: 14,
    name: "ZIndex",
    date: "2023-07-02",
    plays: [
      {
        id: 77,
        name: "Notes",
        solution: require("./077-notes"),
        date: "2023-07-02",
      },
      {
        id: 78,
        name: "Ukulele",
        solution: require("./078-ukulele"),
        date: "2023-07-02",
      },
      {
        id: 79,
        name: "Tambourine",
        solution: require("./079-tambourine"),
        date: "2023-07-02",
      },
      {
        id: 80,
        name: "Piano",
        solution: require("./080-piano"),
        date: "2023-07-02",
      },
    ],
  },
  {
    id: 15,
    name: "Filter",
    date: "2023-07-10",
    plays: [
      {
        id: 81,
        name: "Odoo",
        solution: require("./081-odoo"),
        date: "2023-07-10",
      },
      {
        id: 82,
        name: "Diamond Cut",
        solution: require("./082-diamond-cut"),
        date: "2023-07-10",
      },
      {
        id: 83,
        name: "Supernova",
        solution: require("./083-supernova"),
        date: "2023-07-10",
      },
      {
        id: 84,
        name: "Junction",
        solution: require("./084-junction"),
        date: "2023-07-10",
      },
      {
        id: 85,
        name: "Pythagoras",
        solution: require("./085-pythagoras"),
        date: "2023-07-10",
      },
      {
        id: 86,
        name: "Stairway",
        solution: require("./086-stairway"),
        date: "2023-07-10",
      },
      {
        id: 87,
        name: "Building Blocks",
        solution: require("./087-building-blocks"),
        date: "2023-07-10",
      },
      {
        id: 88,
        name: "Tight Corner",
        solution: require("./088-tight-corner"),
        date: "2023-07-10",
      },
    ],
  },
  {
    id: 16,
    name: "Aspect",
    date: "2023-07-30",
    plays: [
      {
        id: 89,
        name: "Summit",
        solution: require("./089-summit"),
        date: "2023-07-30",
      },
      {
        id: 90,
        name: "Eclipse",
        solution: require("./090-eclipse"),
        date: "2023-07-30",
      },
      {
        id: 91,
        name: "Reflection",
        solution: require("./091-reflection"),
        date: "2023-07-30",
      },
      {
        id: 92,
        name: "Squeeze",
        solution: require("./092-squeeze"),
        date: "2023-07-30",
      },
      {
        id: 93,
        name: "Great Wall",
        solution: require("./093-great-wall"),
        date: "2023-07-30",
      },
      {
        id: 94,
        name: "Ripples",
        solution: require("./094-ripples"),
        date: "2023-07-30",
      },
      {
        id: 95,
        name: "Pokeball",
        solution: require("./095-pokeball"),
        date: "2023-07-30",
      },
      {
        id: 96,
        name: "Mandala",
        solution: require("./096-mandala"),
        date: "2023-07-30",
      },
    ],
  },
  {
    id: 24,
    name: "Offset",
    date: "2023-04-22",
    plays: [
      {
        id: 143,
        name: "Simply Circle",
        solution: require("./143-simply-circle"),
        date: "2023-04-22",
      },
      {
        id: 144,
        name: "Long Heart",
        solution: require("./144-long-heart"),
        date: "2023-04-22",
      },
      {
        id: 145,
        name: "Spotlight",
        solution: require("./145-spotlight"),
        date: "2023-04-22",
      },
      {
        id: 146,
        name: "Streaks",
        solution: require("./146-streaks"),
        date: "2023-04-22",
      },
      {
        id: 147,
        name: "Splash",
        solution: require("./147-splash"),
        date: "2023-04-22",
      },
      {
        id: 148,
        name: "Eight",
        solution: require("./148-eight"),
        date: "2023-04-22",
      },
      {
        id: 149,
        name: "Earthworm",
        solution: require("./149-earthworm"),
        date: "2023-04-22",
      },
      {
        id: 150,
        name: "Finger Heart",
        solution: require("./150-finger-heart"),
        date: "2023-04-22",
      },
    ],
  },
  {
    id: 25,
    name: "Flex",
    date: "2023-06-29",
    plays: [
      {
        id: 151,
        name: "Pawn",
        solution: require("./151-pawn"),
        date: "2023-06-29",
      },
      {
        id: 152,
        name: "Rook",
        solution: require("./152-rook"),
        date: "2023-06-29",
      },
      {
        id: 153,
        name: "Checkers",
        solution: require("./153-checkers"),
        date: "2023-06-29",
      },
      {
        id: 154,
        name: "Poker Chip",
        solution: require("./154-poker-chip"),
        date: "2023-06-29",
      },
      {
        id: 155,
        name: "Snake and symbol",
        solution: require("./155-snake-and-symbol"),
        date: "2023-06-29",
      },
      {
        id: 156,
        name: "Chinese checkers",
        solution: require("./156-chinese-checkers"),
        date: "2023-06-29",
      },
      {
        id: 157,
        name: "Monopoly",
        solution: require("./157-monopoly"),
        date: "2023-06-29",
      },
      {
        id: 158,
        name: "Clubs",
        solution: require("./158-clubs"),
        date: "2023-06-29",
      },
    ],
  },
  {
    id: 26,
    name: "Initial",
    date: "2023-09-18",
    plays: [
      {
        id: 159,
        name: "Portal",
        solution: require("./159-portal"),
        date: "2023-09-18",
      },
      {
        id: 160,
        name: "Donut",
        solution: require("./160-donut"),
        date: "2023-09-18",
      },
      {
        id: 161,
        name: "Converge",
        solution: require("./161-converge"),
        date: "2023-09-18",
      },
      {
        id: 162,
        name: "Chevron",
        solution: require("./162-chevron"),
        date: "2023-09-18",
      },
      {
        id: 163,
        name: "Missing Piece",
        solution: require("./163-missing-piece"),
        date: "2023-09-18",
      },
      {
        id: 164,
        name: "Rangoli",
        solution: require("./164-rangoli"),
        date: "2023-09-18",
      },
      {
        id: 165,
        name: "Pyramid",
        solution: require("./165-pyramid"),
        date: "2023-09-18",
      },
      {
        id: 166,
        name: "Flow",
        solution: require("./166-flow"),
        date: "2023-09-18",
      },
    ],
  },
  {
    id: 27,
    name: "Relative",
    date: "2023-09-28",
    plays: [
      {
        id: 167,
        name: "React India",
        solution: require("./167-react-india"),
        date: "2023-09-28",
      },
      {
        id: 168,
        name: "Carpet",
        solution: require("./168-carpet"),
        date: "2023-09-28",
      },
      {
        id: 169,
        name: "Abstract Plate",
        solution: require("./169-abstract-plate"),
        date: "2023-10-12",
      },
      {
        id: 170,
        name: "Party Hat",
        solution: require("./170-party-hat"),
        date: "2023-09-28",
      },
    ],
  },
  {
    id: 28,
    name: "Revert",
    date: "2023-11-08",
    plays: [
      {
        id: 171,
        name: "Pumpkin",
        solution: require("./171-pumpkin"),
        date: "2023-11-08",
      },
      {
        id: 172,
        name: "Crossbones",
        solution: require("./172-crossbones"),
        date: "2023-11-08",
      },
      {
        id: 173,
        name: "Hockey Mask",
        solution: require("./173-hockey-mask"),
        date: "2023-11-08",
      },
      {
        id: 174,
        name: "Witch's Hat",
        solution: require("./174-witch's-hat"),
        date: "2023-11-08",
      },
      {
        id: 175,
        name: "Evil cat",
        solution: require("./175-evil-cat"),
        date: "2023-11-08",
      },
      {
        id: 176,
        name: "Castlevania",
        solution: require("./176-castlevania"),
        date: "2023-11-08",
      },
      {
        id: 178,
        name: "Candy",
        solution: require("./178-candy"),
        date: "2023-11-08",
      },
    ],
  },
];
