name: aws_integration
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: aws_integration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check that bucket exists
        id: bucket-check
        continue-on-error: true
        run: |
          set +e
          S3_CHECK_RESULT=$(aws s3api head-bucket --output text --bucket test 2>&1)
          ERROR_CODE=$?
          echo S3_CHECK_RESULT=${S3_CHECK_RESULT//[\(\)]/_} >> $GITHUB_OUTPUT
          set -e
          exit $ERROR_CODE
      - name: check access
        if: steps.bucket-check.outcome == 'failure'
        run: |
          if echo "${{ steps.bucket-check.outputs.S3_CHECK_RESULT }}" | grep 'Forbidden';
          then
            echo "Access dined"
            exit 254
          fi
