name: aws_integration_cleanup
on: workflow_dispatch
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: aws_integration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: remove bucket
        run: |
          aws s3 rm s3://${{ vars.AWS_BUCKET_NAME }} --recursive 
          aws s3api delete-bucket --bucket ${{ vars.AWS_BUCKET_NAME }} --region ${{ vars.AWS_REGION }}
