name: aws_integration
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: aws_integration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check that bucket exists
        id: bucket-check
        run: |
          S3_CHECK_RESULT=$(aws s3api head-bucket --output text --bucket ${{ vars.AWS_BUCKET_NAME }})
          echo "IS_NOT_PERMISSIONS=$S3_CHECK_RESULT | grep -c 'Forbidden'"
          echo "IS_NOT_EXISTED=$S3_CHECK_RESULT | grep -c 'Not Found'"
          echo ${{env.IS_NOT_PERMISSIONS}}
          echo ${{env.IS_NOT_EXISTED}}

# `aws s3api head-bucket --output text --bucket test` >> $IS_NOT_EXISTED
# `aws s3api head-bucket --output text --bucket css_battle` >> $IS_NOT_PERMISSIONS
# echo S3_CHECK_RESULT >> $TEST
# echo $S3_CHECK_RESULT1 | grep -c 'Forbidden' >> $IS_NOT_PERMISSIONS
# echo $S3_CHECK_RESULT2 | grep -c 'Not Found' >> $IS_NOT_EXISTED
