name: aws_integration
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: aws_integration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check that bucket exists
        run: echo "S3_CHECK_RESULT=$(aws s3api head-bucket --output text --bucket test)" >> $GITHUB_ENV
      - name: access dined
        if: contains(env.S3_CHECK_RESULT, 'Forbidden')
        run: |
          echo "Access to ${{ vars.AWS_BUCKET_NAME }} is dined"
          exit 1

# `aws s3api head-bucket --output text --bucket test` >> $IS_NOT_EXISTED
# `aws s3api head-bucket --output text --bucket css_battle` >> $IS_NOT_PERMISSIONS
# echo S3_CHECK_RESULT >> $TEST
# echo $S3_CHECK_RESULT1 | grep -c 'Forbidden' >> $IS_NOT_PERMISSIONS
# echo $S3_CHECK_RESULT2 | grep -c 'Not Found' >> $IS_NOT_EXISTED
