name: aws_integration
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: aws_integration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check that bucket exists
        id: bucket-check
        run: |
          if aws s3api head-bucket --output text --bucket battle-test
          then
            echo "S3_CHECK_RESULT=true" >> "$GITHUB_OUTPUT"
          else
            echo "S3_CHECK_RESULT=false" >> "$GITHUB_OUTPUT"
          fi
          echo $S3_CHECK_RESULT
      - name: temporary
        run: |
          echo ${{steps.bucket-check.outputs.S3_CHECK_RESULT}}
          echo ${{env.S3_CHECK_RESULT}}
      #- name: access dined
      #  if: contains(steps.bucket-check.env.S3_CHECK_RESULT, 'Forbidden')
      #  run: |
      #    echo "Access to ${{ vars.AWS_BUCKET_NAME }} is dined"
      #    exit 1

# `aws s3api head-bucket --output text --bucket test` >> $IS_NOT_EXISTED
# `aws s3api head-bucket --output text --bucket css_battle` >> $IS_NOT_PERMISSIONS
# echo S3_CHECK_RESULT >> $TEST
# echo $S3_CHECK_RESULT1 | grep -c 'Forbidden' >> $IS_NOT_PERMISSIONS
# echo $S3_CHECK_RESULT2 | grep -c 'Not Found' >> $IS_NOT_EXISTED
