name: aws_integration
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: aws_integration
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check that bucket exists
        id: bucket-check
        run: |
          S3_CHECK_RESULT=`aws s3api head-bucket --output text --bucket ${{ vars.AWS_BUCKET_NAME }}`
          S3_CHECK_RESULT1=`aws s3api head-bucket --output text --bucket test`
          S3_CHECK_RESULT2=`aws s3api head-bucket --output text --bucket css_battle`
          echo S3_CHECK_RESULT >> $TEST
          echo $S3_CHECK_RESULT1 | grep -c 'Forbidden' >> $IS_NOT_PERMISSIONS
          echo $S3_CHECK_RESULT2 | grep -c 'Not Found' >> $IS_NOT_EXISTED
      - name: temporary
        run: |
          echo ${{steps.bucket-check.outputs.TEST}}
          echo ${{steps.bucket-check.outputs.IS_NOT_EXISTED}}
          echo ${{steps.bucket-check.outputs.IS_NOT_PERMISSIONS}}
