name: beget_integration_cleanup
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: beget_integration
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: cleanup
        shell: python
        run: |
          import ftplib
          import shutil
          import os
          ftp = ftplib.FTP_TLS('${{ vars.USER_ID }}.beget.tech')
          ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
          def deletedir(dirname):
            ftp.cwd(dirname)
            print(dirname)
            for file in ftp.nlst():
              try:
                ftp.delete(file)
              except Exception:
                deletedir(file)
              ftp.cwd("..")
              ftp.rmd(dirname)
          deletedir('${{ vars.ROOT_DIRECTORY }}')
