name: beget_integration_cleanup
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: beget_integration
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: cleanup
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ vars.USER_ID }}.beget.tech
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: "${{ vars.ROOT_DIRECTORY }}"
          options: "--delete"
