name: deploy
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clean
        run: |
          branchList=`git branch --remotes`
          for branch in $branchList
          do
            name=`echo $branch | cut -d "/" -f 2`
            if [ $name != master -a $name != develop -a $name != gh-pages ]
            then
              echo $name
            fi
          done
