name: deploy
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clean
        run: |
          for branch in git branch -a
          do
            echo "Mendax Current number: $branch"
          done
